### ISSUE TITLE
Merge resource behaviour in Python3 / Iris v2

### ISSUE THREAD

**Issue by dkillick** [SciTools/courses#134] opened 2018-04-27 13:52 UTC
When using Python3 & Iris v2, the resources for the merge exercise load differently to using Python2 and Iris v1. Specifically, it appears like each dataset is loaded twice. This needs to be fixed, preferably for consistent behaviour between the two Python/Iris combinations.

Investigate:
* is this being caused by Python 3 (i.e. has wildcard filename match behaviour changed?)
* is this being caused by Iris v2 (i.e. has dataset load behaviour changed in a manner that we have not allowed for?)
* is this being caused by a combination of the above?
* is this being caused by something else?

**Comment by dkillick** [comment] 2018-04-27 13:52
Ping @kaedonkers

**Comment by kaedonkers** [comment] 2018-05-24 10:08
The example that this issue presented in is using `iris.load_raw()` on a netCDF file containing a single `air_potential_temperature` phenomenon.

Py2+Iris1 loads a single cube, as expected.

Py3+Iris2 loads two cubes: `air_potential_temperature` and `surface_altitude`.
`surface_altitude` is not a cube but an Auxiliary coordinate of the `air_potential_temperature` cube.

![iris2_load_issue](https://user-images.githubusercontent.com/32906197/40479013-77256d10-5f42-11e8-81dc-a73de041dc5d.png)

Investigation (after testing with Py2+Iris1, Py2+Iris2, Py3+Iris2): 
:x: Is this being caused by Python 3?
:heavy_check_mark: Is this being caused by Iris v2?
:x: Is this being caused by `iris.load_raw()`?

**Comment by kaedonkers** [comment] 2018-05-24 10:20
**Iris v1.13:**
![iris1 13](https://user-images.githubusercontent.com/32906197/40479665-1d9e3cca-5f44-11e8-9cdb-06f1ca67a7d6.png)

**Iris v2.0:**
![iris2 0](https://user-images.githubusercontent.com/32906197/40479666-1db9c580-5f44-11e8-8eeb-8e47653728cc.png)

**Comment by pelson** [comment] 2018-07-12 13:05
I think you are pointing to the fact that netcdf_promote became the default behaviour in iris 2? https://github.com/SciTools/iris/issues/1723

**Comment by kaedonkers** [comment] 2018-07-12 14:36
Thanks for a response on this @pelson. Looks like we will need to change the resources used for this exercise.

**Comment by kaedonkers** [comment] 2018-11-29 10:23
This has been fixed by loading with a constriant.

**Closed by kaedonkers** 2018-11-29 10:23 UTC
